### ISSUE TITLE
Android X upgrade

### ISSUE THREAD

**Issue by bradintheusa** [AmolGangadhare/flutter_barcode_scanner#1]
Hi

Will this be upgraded to use Android X?

Thanks

**Comment by AmolGangadhare** [comment]
Hi @bradintheusa , 
I was preparing for this earlier 😃. I've updated the Android project that will now support 'Android X'. I'll be testing this thoroughly and will update you shortly on this. 
Thanks

**Comment by AmolGangadhare** [comment]
Hi @bradintheusa ,
I've updated the plugin to the pub, now you can use it. In case you face any issue please feel free to report it. Please update on this so I can close the issue. 
Thanks
