### ISSUE TITLE
iOS - can't link

### ISSUE THREAD

**Issue by davehindle** [AmolGangadhare/flutter_barcode_scanner#105]
Using XCode -> Product -> Archive gives
Undefined symbol: _OBJC_CLASS%__TtC23flutter_barcode_scanner32SwiftFlutterBarcodeScannerPlugin

**Comment by davehindle** [comment]
Using Generic iOS Device

**Comment by AmolGangadhare** [comment]
@davehindle Sorry for this late reply.

Is the issue resolved or still persists?

**Comment by AmolGangadhare** [comment]
Closing this as there is no response from the user.

Feel free to open a new issue if you face any unexpected.

**Comment by Joyker** [comment]
same problem, any solution ?
