### ISSUE TITLE
Deprecated API

### ISSUE THREAD

**Issue by kikoba** [AmolGangadhare/flutter_barcode_scanner#124]
Thank you for your job.
I have a problem if I run your sample program  (emulator with API 21 or API 28) I have this report from compiler:
``Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.``

Do you have a solution to solve this problem?
Thank you

**Comment by totalard** [comment]
I have this issues too.. please fix it.

**Comment by ahkela21** [comment]
I have this issues too..

**Comment by vadimwe** [comment]
+1

**Comment by callmejm** [comment]
+1

**Comment by fabegalo** [comment]
I have this issues too.. please fix it.

**Comment by AmolGangadhare** [comment]
The upcoming release will come up with the new MLKit migration for android. After which this will not be there.

**Comment by AmolGangadhare** [comment]
Closing this issue as there is already an ML Kit migration-related feature request.
