### ISSUE TITLE
AndroidX error

### ISSUE THREAD

**Issue by NTMS2017** [AmolGangadhare/flutter_barcode_scanner#13]
iOS is working and now I am having AndroidX error. Any idea how can I resolve this issue?

```
Launching lib/main.dart on SM G935F in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.core:core' has different version for the compile (1.0.0) and runtime (1.0.1) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUİLD FAILED in 14s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1
```

**Comment by AmolGangadhare** [comment]
Please confirm that.
1. Do you have updated Android Studio?
2. Are you using Kotlin in Android?
3. Have you added any other dependency in the Android part?

Please make sure that in Android you have,

       `compileSdkVersion 28`
        `minSdkVersion 16`
        `targetSdkVersion 28`
in `build.gradle`

**Comment by NTMS2017** [comment]
I am using IntelliJ not Android Studio. and compile sdk and target sdk as same as your post. I have many dependency such as random_color, path_provider, intl, mailer, image_picker, image_crop, encrypt, diacritic, provider, card_settings, utl_launcher and flutter_slidable.

**Comment by AmolGangadhare** [comment]
Hi,
I've checked with the combination of all plugins mentioned. AS there are multiple dependencies used, the error is occurring as the `android` in the project is not `AndroidX` migrated by default. Please follow the below steps.

Open `android` project in flutter app as a new project **-->** Goto `Refactor` and then click on `Migrate to AndroidX` wait till studio migrates the app to AndroidX. 

Please refer https://developer.android.com/jetpack/androidx/migrate for official migration guide.

I'll be looking into the plugin and check for interdependency errors. 
Please let me know if the issue persists after migrating.

**Note: Please take project backup before migration.**

**Comment by NTMS2017** [comment]
Thank you very much, I will look at it now...

**Comment by NTMS2017** [comment]
Following the  https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility, manually migrate my flutter app. Thanks
