### ISSUE TITLE
Touch area size for the flash button

### ISSUE THREAD

**Issue by carlos-cesar** [AmolGangadhare/flutter_barcode_scanner#132]
After publishment of our app on google play store, its was reported some warnings, and one of them is related to the flash button of this plugin.

1. It is reproduced in case of using a device as mentioned below on "Smartphone" and detailed on the screenshot, it is considered a warning regarding the size of the flash button which says: 

"Consider increasing this clickable item. The size of this item is 40dp x 40dp. Consider increasing the width by 48dp and the height by 48dp or more in this touch area. [know more](https://support.google.com/accessibility/android/answer/7101858)"

![Screenshot at 2020-10-29 18-04-19](https://user-images.githubusercontent.com/7138062/97635817-bef10000-1a16-11eb-8ea4-4f47996a8fba.png)
![Screenshot at 2020-10-29 16-05-39](https://user-images.githubusercontent.com/7138062/97635832-c6180e00-1a16-11eb-9415-6a493f602b1f.png)

Smartphone:
 - Device: Pixel 3
 - OS: Android 9

**Comment by AmolGangadhare** [comment]
The icon size in Android has been increased to 48dpx48dp. It will be fixed in the coming release.

**Comment by AmolGangadhare** [comment]
The fix has been made and the new version is available 1.0.2

**Comment by carlos-cesar** [comment]
@AmolGangadhare, thank you!
