### ISSUE TITLE
Crash after scanning - Android

### ISSUE THREAD

**Issue by ArielFerreiro** [AmolGangadhare/flutter_barcode_scanner#137]
**Describe the bug**
When scanning a barcode the application crashes with this error:
```
E/AndroidRuntime(19560): java.lang.RuntimeException: Unable to destroy activity {xxxx/com.amolg.flutterbarcodescanner.BarcodeCaptureActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference
E/AndroidRuntime(19560): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5438)
E/AndroidRuntime(19560): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5472)
E/AndroidRuntime(19560): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
E/AndroidRuntime(19560): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/AndroidRuntime(19560): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(19560): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2270)
E/AndroidRuntime(19560): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(19560): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(19560): 	at android.app.ActivityThread.main(ActivityThread.java:8125)
E/AndroidRuntime(19560): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19560): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime(19560): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
E/AndroidRuntime(19560): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference
E/AndroidRuntime(19560): 	at com.amolg.flutterbarcodescanner.camera.CameraSource$FrameProcessingRunnable.release(CameraSource.java:967)
E/AndroidRuntime(19560): 	at com.amolg.flutterbarcodescanner.camera.CameraSource.release(CameraSource.java:273)
E/AndroidRuntime(19560): 	at com.amolg.flutterbarcodescanner.camera.CameraSourcePreview.release(CameraSourcePreview.java:84)
E/AndroidRuntime(19560): 	at com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.onDestroy(BarcodeCaptureActivity.java:266)
E/AndroidRuntime(19560): 	at android.app.Activity.performDestroy(Activity.java:8219)
E/AndroidRuntime(19560): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1342)
E/AndroidRuntime(19560): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5423)
E/AndroidRuntime(19560): 	... 11 more
```
**To Reproduce**
Just follow the example in the documentation. Nothing done in Android.

**Smartphone (please complete the following information):**
 - Device: Samsung S9
 - OS: Android 10

**Comment by ktw1318** [comment]
I have same issue. where is solution to fix it?

**Comment by thakurkartik1901** [comment]
I also have same issue.

**Comment by akar995** [comment]
same here

**Comment by AnneBullert** [comment]
JFYI: A solution has already been suggested ;)

https://github.com/AmolGangadhare/flutter_barcode_scanner/issues/133#issuecomment-725418500

**Comment by AnneBullert** [comment]
Please don't close this, the fix still must be implemented in the library and a new version distributed!

**Comment by KaungZawHtet** [comment]
same issue here

**Comment by AmolGangadhare** [comment]
The issue has been addressed and the fix will be available in the coming release.

**Comment by tcnesham** [comment]
I am having the same issue. When is the coming release?

**Comment by tcnesham** [comment]
I was looking at the source code mentioned by the exception CameraSource.java:967. It looks like the assert is using a null reference. I tried a release build and the scan worked. 
flutter build apk --release
adb install build/app/outputs/flutter-apk/app-release.apk

Another issue I found to keep in mind however, is that for "buildTypes release" I had to specify 
shrinkResources false
minifyEnabled false

May be related because the minification seems to be causing an issue.

**Comment by AmolGangadhare** [comment]
The potential fix has been made and the new version is available 1.0.2

**Comment by Dev-Heisenberg** [comment]
write this code here!! ------------------------>>>>>>>        
@SuppressLint("Assert")
        void release() {
            assert (mProcessingThread == null || mProcessingThread.getState() == State.TERMINATED);
            if (mDetector != null) {
                mDetector.release();
                mDetector = null;
            }
        }
![99072724-574cc000-2593-11eb-971b-2ee9e3700190](https://user-images.githubusercontent.com/77680109/105047237-1049e200-5a90-11eb-8134-6e1681c1bf7a.png)

**Comment by AmolGangadhare** [comment]
Closing this issue now as the fix has been made. Please refer to the latest V 2.0.0

**Comment by votivemobileankit** [comment]
Unable to destroy activity {com.votive.kurier/io.github.edufolly.fluttermobilevision.ocr.OcrCaptureActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference

**Comment by votivemobileankit** [comment]
Unable to destroy activity {com

.kurier/io.github.edufolly.fluttermobilevision.ocr.OcrCaptureActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference
