### ISSUE TITLE
Label Flash show "F...h"

### ISSUE THREAD

**Issue by lucas-livingnet** [AmolGangadhare/flutter_barcode_scanner#138]
Label Flash show "F...h".
Flash button appears with short name F ... h
Is it possible to adjust?
![WhatsApp Image 2020-12-09 at 12 42 54](https://user-images.githubusercontent.com/62895141/101651701-1cb43700-3a1c-11eb-8a9e-f99dd5f3582c.jpeg)

**Comment by git4slash** [comment]
Possible repeat / duplication of [https://github.com/AmolGangadhare/flutter_barcode_scanner/issues/97](url)

**Comment by AmolGangadhare** [comment]
Please refer to #97 for updates
