### ISSUE TITLE
Cancelling camera prints "-1" and version 1.0.2 crashes on Android.

### ISSUE THREAD

**Issue by DVADeveloper** [AmolGangadhare/flutter_barcode_scanner#147]
### **Is there a way to not print "-1" as a result when you cancel the camera?**

I have tried a lot of things. And only few of the old versions doesn't print anything, but they don't work on iOS.

Version 1.0.2 works perfectly on iOS, except the "-1" result when cancelling. 
However, Android crashes on start when using version 1.0.2 and any of the latest versions. The old version 0.0.9 works perfectly on android, but not iOS. It seems to be outdated on iOS.

**e.g. Version 0.0.9 doesn't print "-1", it's just empty, which I am looking for to work on iOS** 

Another issue found after, is that the flashlight icon on iOS (iPhone Xs) is not visible. There's a text instead showing: "F...h".

**Comment by AmolGangadhare** [comment]
1. Regarding -1 This can be handled in dart code after the barcode is received.
2. For android crashes, please check with V 2.0.0
3. The "F...h" issue has been resolved in V 2.0.0

Closing this as the issues has been addressed in the latest release.

Feel free to open a new issue.
