### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by zacheryson** [AmolGangadhare/flutter_barcode_scanner#150]
**Describe the bug**
`flutter pub get` worked properly. When I tried debugging the app after adding `import 'package:flutter_barcode_scanner/flutter_barcode_scanner.dart';` I got an error saying `FAILURE: Build failed with an exception.`. I have tested this on a new project.

**To Reproduce**
1. Add `flutter_barcode_scanner: ^1.0.2` under the dependencies of a new project and run 'flutter pub get'
2. Run `flutter run`
3. Error

**Expected behavior**
The app is supposed to run properly

Terminal: 

`
[Fatal Error] collection-1.0.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] collection-1.0.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] collection-1.0.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] collection-1.0.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] lifecycle-runtime-2.1.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] lifecycle-runtime-2.1.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] lifecycle-runtime-2.1.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] lifecycle-runtime-2.1.0.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform material-1.0.0.aar (com.google.android.material:material:1.0.0) to match attributes {artifactType=enumerated-runtime-classes, org.gr
adle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\com.google.android.material\material\1.0.0\f83e012c22d2fa
c8fcf23880d7167832b099fa94\material-1.0.0.aar.
         > error in opening zip file
   > Failed to transform appcompat-1.1.0.aar (androidx.appcompat:appcompat:1.1.0) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.ca
tegory=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.appcompat\appcompat\1.1.0\351d3409fe51f3d862bd2b
1bcc0f3b6ded29460e\appcompat-1.1.0.aar.
         > error in opening zip file
   > Failed to transform appcompat-1.1.0.aar (androidx.appcompat:appcompat:1.1.0) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.st
atus=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.appcompat\appcompat\1.1.0\351d3409fe51f3d862bd2b
1bcc0f3b6ded29460e\appcompat-1.1.0.aar.
         > error in opening zip file
   > Failed to transform legacy-support-v4-1.0.0.aar (androidx.legacy:legacy-support-v4:1.0.0) to match attributes {artifactType=enumerated-runtime-classes,
org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.legacy\legacy-support-v4\1.0.0\3e1271b351e120966
1b9fd769cd6681a31678fe\legacy-support-v4-1.0.0.aar.
         > error in opening zip file
   > Failed to transform recyclerview-1.0.0.aar (androidx.recyclerview:recyclerview:1.0.0) to match attributes {artifactType=enumerated-runtime-classes, org.
gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.recyclerview\recyclerview\1.0.0\ee3a2ad35bcfa91a
b9eeebe991b0893ab40009cf\recyclerview-1.0.0.aar.
         > error in opening zip file
   > Failed to transform media-1.0.0.aar (androidx.media:media:1.0.0) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.status=release
, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.media\media\1.0.0\7f92bbaf670497a9a1105124122fb2
0cee61e58c\media-1.0.0.aar.
         > error in opening zip file
   > Failed to transform transition-1.0.0.aar (androidx.transition:transition:1.0.0) to match attributes {artifactType=enumerated-runtime-classes, org.gradle
.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.transition\transition\1.0.0\f3556ce8f251984acb24
014c3ba055ff235929ff\transition-1.0.0.aar.
         > error in opening zip file
   > Failed to transform coordinatorlayout-1.0.0.aar (androidx.coordinatorlayout:coordinatorlayout:1.0.0) to match attributes {artifactType=enumerated-runtim
e-classes, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.coordinatorlayout\coordinatorlayout\1.0.0\766438
5a7e39112b780baf8819ee880dcd3c4094\coordinatorlayout-1.0.0.aar.
         > error in opening zip file
   > Failed to transform slidingpanelayout-1.0.0.aar (androidx.slidingpanelayout:slidingpanelayout:1.0.0) to match attributes {artifactType=enumerated-runtim
e-classes, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.slidingpanelayout\slidingpanelayout\1.0.0\37eba9
ccbf09b75cc4aa78a5e182d5b8ba79ad6a\slidingpanelayout-1.0.0.aar.
         > error in opening zip file
   > Failed to transform vectordrawable-animated-1.1.0.aar (androidx.vectordrawable:vectordrawable-animated:1.1.0) to match attributes {artifactType=enumerat
ed-runtime-classes, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.vectordrawable\vectordrawable-animated\1.1.0\fcd
a1161354501471c30a4e077af6b5c4d4eddc6\vectordrawable-animated-1.1.0.aar.
         > error in opening zip file
   > Failed to transform vectordrawable-1.1.0.aar (androidx.vectordrawable:vectordrawable:1.1.0) to match attributes {artifactType=enumerated-runtime-classes
, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.vectordrawable\vectordrawable\1.1.0\eac7a364fff5
34035a2a6cb17770a1288315f69f\vectordrawable-1.1.0.aar.
         > error in opening zip file
   > Failed to transform vectordrawable-1.1.0.aar (androidx.vectordrawable:vectordrawable:1.1.0) to match attributes {artifactType=enumerated-runtime-classes
, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.vectordrawable\vectordrawable\1.1.0\eac7a364fff5
34035a2a6cb17770a1288315f69f\vectordrawable-1.1.0.aar.
         > error in opening zip file
   > Failed to transform swiperefreshlayout-1.0.0.aar (androidx.swiperefreshlayout:swiperefreshlayout:1.0.0) to match attributes {artifactType=enumerated-run
time-classes, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.swiperefreshlayout\swiperefreshlayout\1.0.0\4fd2
65b80a2b0fbeb062ab2bc4b1487521507762\swiperefreshlayout-1.0.0.aar.
         > error in opening zip file
   > Failed to transform asynclayoutinflater-1.0.0.aar (androidx.asynclayoutinflater:asynclayoutinflater:1.0.0) to match attributes {artifactType=enumerated-
runtime-classes, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.asynclayoutinflater\asynclayoutinflater\1.0.0\5f
fa788d19a6863799f25cb50d4fdfb0ec649037\asynclayoutinflater-1.0.0.aar.
         > error in opening zip file
   > Failed to transform cursoradapter-1.0.0.aar (androidx.cursoradapter:cursoradapter:1.0.0) to match attributes {artifactType=enumerated-runtime-classes, o
rg.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.cursoradapter\cursoradapter\1.0.0\74014983a86b83
cbce534dec4e7aa9312f5f5d82\cursoradapter-1.0.0.aar.
         > error in opening zip file
   > Failed to transform cursoradapter-1.0.0.aar (androidx.cursoradapter:cursoradapter:1.0.0) to match attributes {artifactType=enumerated-runtime-classes, o
rg.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.cursoradapter\cursoradapter\1.0.0\74014983a86b83
cbce534dec4e7aa9312f5f5d82\cursoradapter-1.0.0.aar.
         > error in opening zip file
   > Failed to transform cardview-1.0.0.aar (androidx.cardview:cardview:1.0.0) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.statu
s=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.cardview\cardview\1.0.0\158dbc2e2bc502815821191b
04446b8f663c1874\cardview-1.0.0.aar.
         > error in opening zip file
   > Failed to transform documentfile-1.0.0.aar (androidx.documentfile:documentfile:1.0.0) to match attributes {artifactType=enumerated-runtime-classes, org.
gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.documentfile\documentfile\1.0.0\66104345c90cd8c2
fd5ad2d3aad692b280e10c32\documentfile-1.0.0.aar.
         > error in opening zip file
   > Failed to transform localbroadcastmanager-1.0.0.aar (androidx.localbroadcastmanager:localbroadcastmanager:1.0.0) to match attributes {artifactType=enume
rated-runtime-classes, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.localbroadcastmanager\localbroadcastmanager\1.0.
0\2734f31c8321e83ce6b60570d14777fc33cc2ece\localbroadcastmanager-1.0.0.aar.
         > error in opening zip file
   > Failed to transform print-1.0.0.aar (androidx.print:print:1.0.0) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.status=release
, org.gradle.usage=java-runtime}.
      > Execution failed for AarToClassTransform: C:\Users\zache\.gradle\caches\modules-2\files-2.1\androidx.print\print\1.0.0\7722094652c48ebe27acc94d74a55e
759e4635ff\print-1.0.0.aar.
         > error in opening zip file

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        12.9s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin flutter_barcode_scanner...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                 2,970ms

[Fatal Error] collection-1.0.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] lifecycle-runtime-2.1.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] collection-1.0.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] lifecycle-runtime-2.1.0.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileReleaseAidl'.
> Could not resolve all task dependencies for configuration ':releaseCompileClasspath'.
   > Could not resolve androidx.lifecycle:lifecycle-runtime:2.1.0.
     Required by:
         project : > androidx.core:core:1.1.0
      > Could not resolve androidx.lifecycle:lifecycle-runtime:2.1.0.
         > Could not parse POM https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-runtime/2.1.0/lifecycle-runtime-2.1.0.pom
            > Content is not allowed in prolog.
   > Could not resolve androidx.lifecycle:lifecycle-runtime:2.1.0.
     Required by:
         project : > androidx.activity:activity:1.0.0
      > Could not resolve androidx.lifecycle:lifecycle-runtime:2.1.0.
         > Could not parse POM https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-runtime/2.1.0/lifecycle-runtime-2.1.0.pom
            > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Exception: The plugin flutter_barcode_scanner could not be built due to the issue above.
`

**Comment by johandb** [comment]
Did you copy the example project to your new project ? Does it still crash. I have no problems using version 2.0.0 on a new project and copy the example in my project.

**Comment by AmolGangadhare** [comment]
@zacheryson 
Is the issue still persists for you?

**Comment by zacheryson** [comment]
Hi, sorry I just saw this. It worked once I reinstalled android studio
