### ISSUE TITLE
warning: Camera.Parameters in Camera has been deprecated

### ISSUE THREAD

**Issue by eduardofcr** [AmolGangadhare/flutter_barcode_scanner#156]
After upgrade flutter, the build process generates a lot os warnings :

.pub-cache/hosted/pub.dartlang.org/flutter_barcode_scanner-1.0.2/android/src/main/java/com/amolg/flutterbarcodescanner/BarcodeCaptureActivity.java:230: warning: [deprecation] FOCUS_MODE_CONTINUOUS_PICTURE in Camera.Parameters has been deprecated
                    autoFocus ? Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE : null);

.pub-cache/hosted/pub.dartlang.org/flutter_barcode_scanner-1.0.2/android/src/main/java/com/amolg/flutterbarcodescanner/BarcodeCaptureActivity.java:211: warning: [deprecation] ACTION_DEVICE_STORAGE_LOW in Intent has been deprecated
            IntentFilter lowstorageFilter = new IntentFilter(Intent.ACTION_DEVICE_STORAGE_LOW);

.pub-cache/hosted/pub.dartlang.org/flutter_barcode_scanner-1.0.2/android/src/main/java/com/amolg/flutterbarcodescanner/BarcodeCaptureActivity.java:234: warning: [deprecation] Camera in android.hardware has been deprecated
                .setFlashMode(useFlash ? Camera.Parameters.FLASH_MODE_TORCH : null)

.pub-cache/hosted/pub.dartlang.org/flutter_barcode_scanner-1.0.2/android/src/main/java/com/amolg/flutterbarcodescanner/BarcodeCaptureActivity.java:421: warning: [deprecation] Camera in android.hardware has been deprecated
                flashMode = isFlashToBeTurnOn ? Camera.Parameters.FLASH_MODE_TORCH : Camera.Parameters.FLASH_MODE_OFF;

**Comment by AmolGangadhare** [comment]
@eduardofcr 
Thanks for raising the issue.

Please ignore the warnings as of now. The ML Kit migration is underway, it will not be there after ML Kit migration.

Thanks
