### ISSUE TITLE
No Swift version set

### ISSUE THREAD

**Issue by rgbinnovation** [AmolGangadhare/flutter_barcode_scanner#16]
- `flutter_barcode_scanner` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by AmolGangadhare** [comment]
You may have not added SWIFT support for iOS.
Please refer,

Deployment target: 10 Swift Version: 5

As iOS code is written in Swift so you need to convert your existing iOS codebase to swift (or if you are creating a new project from Android Studio make sure to check Include Swift support for iOS code.) To do that you can create a new project with the same name in a different location and then just copy iOS folder to existing. (if any changes made before make sure to add these in iOS(swift)). After making codebase in swift make sure that the Swift version is 5 as the code for iOS is written in Swift 5. To use on iOS, open the Xcode and add camera usage description in Info.plist.

```
<key>NSCameraUsageDescription</key>
<string>Camera permission is required for barcode scanning.</string>
```

**Comment by rgbinnovation** [comment]
Ok, fixed this in a similar fashion. I just had to ass a single empty Swift file to my iOS project and SWIFT is added and you can set the version as per above. However now there is a new issue. Will make a new post.

**Comment by AmolGangadhare** [comment]
Have you also added a `Bridging Header` file along with swift file?
