### ISSUE TITLE
Qr Scretched on camera

### ISSUE THREAD

**Issue by kttary** [AmolGangadhare/flutter_barcode_scanner#164]
Im using flutter barcode scanner 1.0.2. Usually the qrcode shape is square but on my android it is not. It is scretched.

![Screenshot_20210306-212344](https://user-images.githubusercontent.com/39557649/110208675-8b8e1880-7ec3-11eb-9051-ac0b77c3b22a.jpg)

What wrong?

**Comment by AmolGangadhare** [comment]
Seems to be a duplicate of #109 Please refer to #109  further update
