### ISSUE TITLE
Application falls down

### ISSUE THREAD

**Issue by Evoswork** [AmolGangadhare/flutter_barcode_scanner#165]
Hi, the application falls down in nullsafety branch during debugging. CameraSource class in 965 line while checking
`assert (mProcessingThread.getState() == State.TERMINATED);`
Error:
`Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference`
The mistake was found on the 29th android emulator.
MacOs 11.2.2

**Comment by vinicmg** [comment]
Same here on Pixel 4a running Android 12 Developer Preview (Sunfish-spp1.210)

**Comment by excode** [comment]
Any  solution for this ???

**Comment by AmolGangadhare** [comment]
The potential fix has been made in PR #168
