### ISSUE TITLE
pls procceed to full Null-safety 

### ISSUE THREAD

**Issue by ahmadjehad** [AmolGangadhare/flutter_barcode_scanner#175]

**Comment by excode** [comment]
Same for me ...  waiting the null safe :-(

**Comment by ahmadjehad** [comment]
its sad 
i really loved this package , i hope they get there asap because i'm using it anyway without  null-safety in my app 😢

**Comment by eliasayele** [comment]
Where is the author?

**Comment by mono0926** [comment]
I've forked this repository and created [barcode_scan2](https://pub.dev/packages/barcode_scan2) with sound null safety🎉

**Comment by AmolGangadhare** [comment]
The migration is done and will be available in the next release.
You can expect a new release very soon

**Comment by AmolGangadhare** [comment]
The V 2.0.0 comes with null safety

Closing this issue, please feel free to open a new issue if the issue still persist
