### ISSUE TITLE
Do not close the scanning activity after every scan.

### ISSUE THREAD

**Issue by Baileypollard** [AmolGangadhare/flutter_barcode_scanner#18]
**Is your feature request related to a problem? Please describe.**
My customers need a way to scan products quickly, thus meaning that they need the activity to stay open after a scan has happened so that they can scan the next item. 

**Describe the solution you'd like**
Give an optional parameter for closing the scan activity after every scan.

**Describe alternatives you've considered**
None that I can think of.

**Additional context**
None.

**Comment by AmolGangadhare** [comment]
Thanks for using the plugin. 
That's a good idea to have continuous scanning. First will have to go through that if it is possible to make continuous streaming from native to dart. I'll update you on this soon.

**Comment by Baileypollard** [comment]
@AmolGangadhare Why not just handle the scanning in through a dart camera widget, that way all the camera view can be added directly in the dart code?

**Comment by AmolGangadhare** [comment]
hi, the plugin has been updated with continuous scan support. Please try it out and provide your feedback. Thanks

**Comment by afornes** [comment]
I've tried continuous scan on Android. It opens the viewer but never finds any barcode

**Comment by AmolGangadhare** [comment]
@afornes thanks for using the plugin. It scans continuously whenever a barcode is scanned. Is there any error logs?

**Comment by afornes** [comment]
@AmolGangadhare There are no errors. I've set breakpoints and also prints inside the "listen" callback and they are never triggered

**Comment by AmolGangadhare** [comment]
sounds weird, give me some time to figure it out. One more thing, is that specific to a QR code or barcode? can you provide a sample you are referring(if possible)?

**Comment by afornes** [comment]
I'm trying to scan an EAN13 barcode. This is the code I'm trying to scan: 8434506077280
Generated with [this tool](https://barcode.tec-it.com/en/EAN13?data=8434506077280).

I've tried using other libraries and it works fine

**Comment by AmolGangadhare** [comment]
@afornes thanks for details, I'm looking into it and will update you shortly on this.

**Comment by AmolGangadhare** [comment]
@afornes it was a threading issue in the plugin bridge. I've made a fix to this. Will test it thoroughly, and upload the latest version to the pub shortly. Thanks for helping to improve this plugin.

**Comment by AmolGangadhare** [comment]
plugin 0.1.3 is uploaded with issue fix.

**Comment by troncomputers** [comment]
Hi.
Is there a chance to show dialog on every barcode found with `TextField` for quantity? I'm trying to fire `showDialog()` inside `getBarcodeStreamReceiver("#ff6666", "Cancel", true).listen((barcode) {}` but it's openning only after I click `Cancel`, not during scanning.

**Comment by irperera** [comment]
can someone point me in the right direction? I need to know how to use the continuous scan.

**Comment by AmolGangadhare** [comment]
> Hi.
> Is there a chance to show dialog on every barcode found with `TextField` for quantity? I'm trying to fire `showDialog()` inside `getBarcodeStreamReceiver("#ff6666", "Cancel", true).listen((barcode) {}` but it's openning only after I click `Cancel`, not during scanning.

Sorry for the late reply. 

Showing an alert dialog in `getBarcodeStreamReceiver` won't work well.
This has to be done in plugin code.

**Comment by troncomputers** [comment]
@irperera 
I did a quick workaround 
```dart
var barcode = await _searchByBarcode();
while (barcode.isNotEmpty) {
    barcode = await _searchByBarcode();
});
```
```dart
Future<String> _searchByBarcode() async {
String barcodeScanRes;
try {
      barcodeScanRes = await FlutterBarcodeScanner.scanBarcode("#ff6666", "Anuluj", true);
} on PlatformException {
        barcodeScanRes = 'Failed to get platform version.';
      }
    return barcodeScanRes;
  }
```

**Comment by AmolGangadhare** [comment]
For continuous scan, there is a method `getBarcodeStreamReceiver`. It will return continuous barcode stream until user press cancel button.
```
FlutterBarcodeScanner.getBarcodeStreamReceiver("#ff6666", "Cancel", false)
         .listen((barcode) { 
         /// barcode to be used
         });
```

**Comment by troncomputers** [comment]
@AmolGangadhare 
I can't use `getBarcodeStreamReceiver` in my case, because I am asking a user for an amount of read products.

**Comment by AmolGangadhare** [comment]
Ok. 
After the platform views become stable we can embed the barcode scanning screen in the app itself.

**Comment by irperera** [comment]
@troncomputers 
I got the scan to work, 

`Future<void> startBarcodeScanStream() async {
    FlutterBarcodeScanner.getBarcodeStreamReceiver("#ed0001", "Done", false)
        .listen((barcode) {
      _scanBarcode = barcode;
      setState(() {
        codes.add(_scanBarcode);
      });
    });
  }`

how can I prompt the user that they are actually scanning.

**Comment by troncomputers** [comment]
@irperera 
That is why I used `FlutterBarcodeScanner.scanBarcode()` in a while loop. There is no "found barcode" event In `getBarcodeStreamReceiver`.

**Comment by irperera** [comment]
@troncomputers 

thanks, I need continuous scanning, can you show me how to do that. 

thanks again.

**Comment by troncomputers** [comment]
I did show you and you gave me "thumbs up" 🤔 
[Continuous  scanning in this thread](https://github.com/AmolGangadhare/flutter_barcode_scanner/issues/18#issuecomment-528213059)

**Comment by irperera** [comment]
thanks I'll try it

**Comment by irperera** [comment]
@troncomputers 
where in the code you put the dialog?

**Comment by troncomputers** [comment]
@irperera 
I have a button to initialize scanning

**Comment by AmolGangadhare** [comment]
This feature has been included in the plugin so closing this.

**Comment by waseemsourcecode** [comment]
Hello I’m using your plugin and it works very well but there is one thing missing that’s is the auto closing it mean what if I want to wait for the result maybe for 10 sec and if it’s not found then I want to close the scanner but I’m unable to close it without pressing cancel button so can you fix that
