### ISSUE TITLE
How to turn off the tips of "Update Google Play services"？

### ISSUE THREAD

**Issue by ChenJunhan** [AmolGangadhare/flutter_barcode_scanner#2]
![image](https://user-images.githubusercontent.com/29296597/54981649-c30b9f00-4fe3-11e9-875f-fa8f10ed7217.png)
There is appear the tips of "Update Google Play services" when i open the barcode_scanner on the emulator and real machine, but i don't have "Google play" on the real machine.How can i turn off the tips?

**Comment by AmolGangadhare** [comment]
Hi,
'**Google play services**' are required. Barcode scanning API which is used in this plugin is dependent on play services. I'll update you on this.
Thanks
