### ISSUE TITLE
Can this works on android phones that dont have gms battery-included ?

### ISSUE THREAD

**Issue by dfang** [AmolGangadhare/flutter_barcode_scanner#20]
**Is your feature request related to a problem? Please describe.**

when i run a demo of this plugin on android emulator, i got this msg.

![image](https://user-images.githubusercontent.com/1277047/60948122-c1f94600-a324-11e9-9fe2-80be45708179.png)

most android phones in China don't have google play services out-of-the-box, so i'm wondering if this can work on a phone that don't have gms ?

Thanks !

**Comment by AmolGangadhare** [comment]
Hi, 
Thanks for using the plugin. 'Play services' is required for the barcode scanner to work as it is dependent on google vision API. So devices which don't have gms it won't run.

**Comment by dfang** [comment]
Get it, 

Thanks !

**Comment by AmolGangadhare** [comment]
I'll update you on this whenever barcode scanning will not be dependent on GMS. Thanks.

**Comment by leihfei** [comment]
how deal this problem;

**Comment by lookfirst** [comment]
Would this fix the issue? https://github.com/AmolGangadhare/flutter_barcode_scanner/issues/35
