### ISSUE TITLE
Barcode scanner after invoking shows just grey screen

### ISSUE THREAD

**Issue by M1chlCZ** [AmolGangadhare/flutter_barcode_scanner#222]
**Describe the bug**
After I fire up the barcode scanner by example provided by the page on pub.dev I am only getting grey screen.
**To Reproduce**
```void _openQRScanner() async {
    try {
      String _content = await FlutterBarcodeScanner.scanBarcode(
          Colors.white24.toString(), "CANCEL", true, ScanMode.DEFAULT);
      setState(() {
        _controllerAddress.text = _content;
      });
    } on PlatformException catch (e) {
      print('Error: $e');
    } on FormatException {
      print('User pressed "back" button before scanning');
    } catch (e) {
      print('Error: $e');
    }
  }
```
**Expected behavior**
To show QR scanner.

**Smartphone (please complete the following information):**
 - Device: Android Emulator, iOS Simulator, Samsung Galaxy A52
 - OS: Android 11, iOS 14.3

**Comment by sarahk** [comment]
I had that too, could run the example code but not mine. I'd changed function names, exceptions. Once I changed all that back it worked. I need to go back and replicate to identify what didn't like being edited.

**Comment by Batflash5** [comment]
Colors.white24.toString() - this is the one which causes error.

The first argument of `FlutterBarcodeScanner.scanBarcode()` is a String(Hex value of color with a '#' replacing '0x').

Example:
`String _content = FlutterBarcodeScanner.scanBarcode('#FF4CAF50', "CANCEL", true, ScanMode.DEFAULT);`

Hope it helps.

**Comment by M1chlCZ** [comment]
@Batflash5 Well that worked, I feel stupid. I already move on to my own solution, out of the curiosity and personal project. However yeah, sometimes reading helps.

So thank you and this is solved.
