### ISSUE TITLE
flutter app crash when running in release mode (flutter run --release)

### ISSUE THREAD

**Issue by AlexsandroZanella2** [AmolGangadhare/flutter_barcode_scanner#223]
Application crashes when running in release mode, but works perfectly in debug

Used latest version (2.0.0).

Example:
`
Future<String> scanQRCode() async {
  try {
    final qrCode = await FlutterBarcodeScanner.scanBarcode(
      '#ff6666',
      'Cancel',
      true,
      ScanMode.QR,
    );
    return qrCode;
  } catch (_) {
    return _;
  }
}
`
StackTrace:
E/AndroidRuntime(27282): java.lang.IllegalAccessError: Illegal class access: 'androidx.appcompat.widget.ContentFrameLayout' attempting to access 'androidx.appcompat.app.u' (declaration of 'androidx.appcompat.widget.ContentFrameLayout' appears in base.apk)
E/AndroidRuntime(27282): 	at androidx.appcompat.widget.ContentFrameLayout.onAttachedToWindow(Unknown Source:7)
E/AndroidRuntime(27282): 	at android.view.View.dispatchAttachedToWindow(View.java:19665)
E/AndroidRuntime(27282): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3458)
E/AndroidRuntime(27282): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3465)
E/AndroidRuntime(27282): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3465)
E/AndroidRuntime(27282): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3465)
E/AndroidRuntime(27282): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3465)
E/AndroidRuntime(27282): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2128)
E/AndroidRuntime(27282): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1819)
E/AndroidRuntime(27282): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7781)
E/AndroidRuntime(27282): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
E/AndroidRuntime(27282): 	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
E/AndroidRuntime(27282): 	at android.view.Choreographer.doFrame(Choreographer.java:789)
E/AndroidRuntime(27282): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
E/AndroidRuntime(27282): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(27282): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(27282): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(27282): 	at android.app.ActivityThread.main(ActivityThread.java:7562)
E/AndroidRuntime(27282): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27282): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(27282): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by AlexsandroZanella2** [comment]
Problema resolvido atualizando gradle e kotlin para as ultimas versões;

**Comment by Dalakoti07** [comment]
@AlexsandroZanella2 can you tell which kotlin version and gradle version?

I am using kotlin version as `1.7.10`

and android gradle version as `4.1.0` 

and gradle version in gradle-wrapper-properties as `7.4` 

and flutter version as `3.3.4 `

and I am still getting this crash

`java.lang.IllegalAccessError: Illegal class access: 'androidx.appcompat.widget.ContentFrameLayout' attempting to access 'androidx.appcompat.app.u' (declaration of 'androidx.appcompat.widget.ContentFrameLayout' appears in base.apk)
E/AndroidRuntime(30705): 	at androidx.appcompat.widget.ContentFrameLayout.onAttachedToWindow(Unknown Source:7)
E/AndroidRuntime(30705): 	at android.view.View.dispatchAttachedToWindow(View.java:19553)
E/AndroidRuntime(30705): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3430)
E/AndroidRuntime(30705): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
E/AndroidRuntime(30705): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
E/AndroidRuntime(30705): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
E/AndroidRuntime(30705): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
E/AndroidRuntime(30705): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2028)
E/AndroidRuntime(30705): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
E/AndroidRuntime(30705): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
E/AndroidRuntime(30705): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
E/AndroidRuntime(30705): 	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
E/AndroidRuntime(30705): 	at android.view.Choreographer.doFrame(Choreographer.java:725)
E/AndroidRuntime(30705): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
E/AndroidRuntime(30705): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(30705): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(30705): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(30705): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(30705): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30705): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(30705): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`
