### ISSUE TITLE
Unable to proceed - Camera not available

### ISSUE THREAD

**Issue by yvesbou** [AmolGangadhare/flutter_barcode_scanner#235]
The UI shows:
"Unable to proceed - Camera not available"

I did the following steps when I landed there:
1. Set minimum deployment target to 12 and set Swift version to 5.
2. Close the Xcode and `run pod install` in `/ios` in flutter project.
3. added this : 

```
<key>NSCameraUsageDescription</key>
<string>Camera permission is required for barcode scanning.</string>  
```

to the `Info.plist` file

4. added `flutter_barcode_scanner: ^2.0.0` to my dependencies
5. import `'package:flutter_barcode_scanner/flutter_barcode_scanner.dart';`
6. added the following code within a streambuilder to my project:

```
stream: FlutterBarcodeScanner.getBarcodeStreamReceiver(
                    "#ff6666", "Cancel", false, ScanMode.DEFAULT)
                ?.map((i) => 'String $i')
```
7.  got this error:

`Error: MissingPluginException(No implementation found for method scanBarcode on channel flutter_barcode_scanner)`

after `flutter run`

8. read your advise on [(https://githubmemory.com/repo/AmolGangadhare/flutter_barcode_scanner/issues/197)](url)
9. flutter clean-> Invalidate Cache and Restart on android studio (I followed the advice on the SO link) ->flutter pub get
 [https://stackoverflow.com/questions/45216264/clear-file-content-cache-in-visual-studio-code](url)

**Screenshots**
<img width="305" alt="Screenshot 2021-10-21 at 15 32 05" src="https://user-images.githubusercontent.com/63062257/138288271-f628e4fb-f140-4438-9401-8c86c57d4b7b.png">

 - Device: iPhone 12 Pro Max - 14.4
 - VS Code

Thank you for your time and effort!

**Comment by cinder92** [comment]
im getting same issue, this is on simulator

**Comment by cinder92** [comment]
@yvesbou you should use a real device. cheers
