### ISSUE TITLE
iOS 12.4 on iphone 6 not requesting permissions correctly

### ISSUE THREAD

**Issue by warriorCoder** [AmolGangadhare/flutter_barcode_scanner#24]
**Describe the bug**
Permissions aren't being correctly requested, only a "grant" option is shown and when pressed takes the user to the ios settings page. There's nowhere to grant permissions and use the camera. 

**To Reproduce**
1. Install per directions (making sure os target is 10, and swift is 5)
2. Click on 'Scan Product button'
4. See permissions issue

**Expected behavior**
The grant permissions to show the ok button and start scanning

**Screenshots**
![UNADJUSTEDNONRAW_thumb_1](https://user-images.githubusercontent.com/4119110/61995900-b95a7c80-b053-11e9-9d1d-22bfe34c64ac.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone6s
 - OS: iOS 12.4
 - Browser n/a
 - Version 0.1.4

**Additional context**

**Comment by AmolGangadhare** [comment]
Thanks for reporting issue. Just to confirm that have you added 
```
<key>NSCameraUsageDescription</key>
<string>Camera permission is required for barcode scanning.</string>
```
Permissions in plist

**Comment by warriorCoder** [comment]
Yup, permission request is in the info.plist file.

**Comment by AmolGangadhare** [comment]
@warriorCoder  Okay, so I tried it on a real device, which is working fine. But when I run it on the simulator it does not show the app in settings. I did some research for this but found no concrete solution. Are you using it on the simulator or a real device?

**Comment by xc43** [comment]
It also did not work with mine. Same device and os. The solution I found was to remove the check for camera permission function and put that part like it was in the previous commit. 

All that in SwiftFlutterBarcodeScannerPlugin.swift 
lines 69 to 81

**Comment by AmolGangadhare** [comment]
@warriorCoder @xc43 
The issue has been fixed in `0.1.5`. Please check it out. Feedbacks are always welcome.

**Comment by xc43** [comment]
Behaves fine by itself now. Also slightly related question: are there any contributing guidelines? I could have tried to correct it but saw that a previous commit was the one that added the code causing the issue.

**Comment by AmolGangadhare** [comment]
@xc43 you can always try it out and contribute to improve this plugin, PRs are always welcome :)
