### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by fmancusomilite** [AmolGangadhare/flutter_barcode_scanner#249]
MissingPluginException: MissingPluginException(No implementation found for method scanBarcode on channel flutter_barcode_scanner)

This issue is present only for Android

**Comment by fmancusomilite** [comment]
I try to flutter clean-> Invalidate Cache and Restart on android studio->flutter pub get but doesn't work

**Comment by pedropacheco92** [comment]
Having the same issue, the actual message is: `No implementation found for method scanBarcode on channel flutter_barcode_scanner`

**Comment by shinlh** [comment]
Same issue here. Any help? I tried everything in this closed issue [7](https://github.com/AmolGangadhare/flutter_barcode_scanner/issues/7). I'm using the latest version 2.0.0.

**Comment by ajfranzoia** [comment]
@AmolGangadhare I'm getting the same error as well. I am using the latest version and tried all the steps given in #7 in a fresh install.
This is my flutter doctor output:

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.3.1 20E241 darwin-arm, locale en-AR)
    • Flutter version 2.5.3 at /Users/augusto/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/augusto/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/augusto/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • Mi 9T (mobile) • f5cc16aa • android-arm64  • Android 10 (API 29)
    • Chrome (web)   • chrome   • web-javascript • Google Chrome 96.0.4664.55

• No issues found!

```

**Comment by asmengistu** [comment]
When using this library make sure you extend FlutterActivty:

Java:
```public class MainActivity extends FlutterActivity {```

Or for Kotlin:
``` class MainActivity: FlutterActivity() { ```

More info here: https://docs.flutter.dev/development/packages-and-plugins/plugin-api-migration

**Comment by KatePsk** [comment]
I faced the same problem in my project. Thanks asmengistu. His solution worked for me. It was really necessary to inherit MainActivity from FlutterActivity. I will just clarify that, of course, it is also necessary to correct the import in MainActivity.

**Comment by alexverbitsky** [comment]
> I faced the same problem in my project. Thanks asmengistu. His solution worked for me. It was really necessary to inherit MainActivity from FlutterActivity. I will just clarify that, of course, it is also necessary to correct the import in MainActivity.

@KatePsk Could you please explain what you've changed and where to solve the issue?

**Comment by alexverbitsky** [comment]
I had the same issue. Previously I've moved from the 1st Flutter version. I had the next code in my MainActivity file

![image](https://user-images.githubusercontent.com/34838543/146528159-0e8c2ae4-970b-43d2-a30d-a3b79a3cee00.png)

Changing code the next way solved my issue

![image](https://user-images.githubusercontent.com/34838543/146528301-a51f16a5-6561-449d-b19b-791efef9c249.png)

**Comment by fmancusomilite** [comment]
**SOLVED**
change from FlutterBarCodeScanner.java all reference to `FlutterActivity` in `FlutterFragmentActivity`. In my case i use in same project local_auth and flutterbarcodescanner packages.

**Comment by nicparmee** [comment]
I think this should just be a temporary fix as some packages need FlutterFragmentActivity
