### ISSUE TITLE
Camera not opened for scan

### ISSUE THREAD

**Issue by brand2021** [AmolGangadhare/flutter_barcode_scanner#289]
Found working in iPhone 11 but following case:
In my phone Redmi note 8 pro, after following code:
                String barcodeScanRes = await FlutterBarcodeScanner.scanBarcode(
                    'ff6666', 'CANCEL', true, ScanMode.BARCODE);

a grey screen opened rather camera scanner.

Result of on clicking that grey screen getting crashed application with following exception:
Exception dispatching input event.
E/MessageQueue-JNI(13828): Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI(13828): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.ScaleGestureDetector.onTouchEvent(android.view.MotionEvent)' on a null object reference
E/MessageQueue-JNI(13828): 	at com.amolg.flutterbarcodescanner.BarcodeCaptureActivity.onTouchEvent(BarcodeCaptureActivity.java:187)

**Comment by OliveiraGusta** [comment]
EN:
MISSING THE #
The # is missing in the argument

'ff6666' - Missing a '#' causes an error.

The first argument of FlutterBarcodeScanner.scanBarcode( ) is a String(Hex color value with a '**#**' replacing '0x').

Example:
`String bardeScanRes = await FlutterBarcodeScanner.scanBarcode(
'#FF6666', 'CANCEL', true, ScanMode.BARCODE);`

I hope I was helpfull

PT-BR:
FALTA O #
Está faltando o # no argumento

'ff6666' - A falta de um '#' causa um erro.

O primeiro argumento de FlutterBarcodeScanner.scanBarcode( ) é um String(Hex color value com um '**#**' substituindo '0x').

Exemplo:
`String bardeScanRes = await FlutterBarcodeScanner.scanBarcode(
'#FF6666', 'CANCEL', true, ScanMode.BARCODE);`

Espero ter te ajudado.



My reference / Minha referencia
> https://github.com/AmolGangadhare/flutter_barcode_scanner/issues/222#issuecomment-942120610

**Comment by brand2021** [comment]
Working with above implementation. Thanks.

**Comment by arslancs** [comment]
Are you still using this plugin? What kind of issues are you currently facing in production? @brand2021
