### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by ghost** [AmolGangadhare/flutter_barcode_scanner#361]
With Android Studio Ladybug | 2024.2.1 :
A problem occurred configuring project ':flutter_barcode_scanner'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.

**Comment by bytelyus** [comment]
+1 ... Had to rebuild project since last year, for a yearly event where we use the scanner, but with new flutter version and brand new project ... :( 

flutter doctor -v

> 
> `[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-x64, locale es-ES)
>     • Flutter version 3.24.3 on channel stable at /Users/.../develop/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 2663184aa7 (3 weeks ago), 2024-09-11 16:27:48 -0500
>     • Engine revision 36335019a8
>     • Dart version 3.5.3
>     • DevTools version 2.37.3
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
>     • Android SDK at /Users/.../Library/Android/sdk
>     • Platform android-34, build-tools 34.0.0
>     • ANDROID_HOME = /Users/.../Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 16.0)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 16A242d
>     • CocoaPods version 1.14.3
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2022.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
> `

**Comment by bytelyus** [comment]
Ok.. found the trick ... by adding this code to project > build.gradle ... 

```

...

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

***** ADD THIS LINES *****

subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    namespace project.group
                }
            }
        }
    }
}

***** TILL HERE *****

subprojects {
    project.evaluationDependsOn(":app")
}

...

```
... good luck @CyrilleP46

**Comment by ghost** [comment]
Thanks, it work.

**Comment by arslancs** [comment]
Are you still using this plugin? What kind of issues are you currently facing in production? @CyrilleP46 @bytelyus

**Comment by kh1amirhamza** [comment]
Check it out , if you have build.gradle.kts,

allprojects {
    repositories {
        google()
        mavenCentral()
    }

    subprojects {
        afterEvaluate {
            if (plugins.hasPlugin("com.android.library")) {
                extensions.configure<com.android.build.gradle.LibraryExtension>("android") {
                    if (namespace == null) {
                        namespace = group.toString()
                    }
                }
            }
        }
    }
}
