### ISSUE TITLE
Gradle sync error

### ISSUE THREAD

**Issue by renan002** [AmolGangadhare/flutter_barcode_scanner#38]
**Describe the bug**
Gradle sync fails every time with message: Android dependency 'com.google.android.gms:play-services-flags' has different version for the compile (16.0.1) and runtime (17.0.0) classpath. You should manually set the same version via DependencyResolution

**Expected behavior**
Gradle sync normaly

**Smartphone (please complete the following information):**
 - Device: Android emolator
 - OS: Android Q

**Comment by AmolGangadhare** [comment]
Try to bump up flutter app android `compileSdkVersion` and `targetSdkVersion` to 29 which is Android 10
