### ISSUE TITLE
Unexpected duplicate tasks:

### ISSUE THREAD

**Issue by JWHAPO** [AmolGangadhare/flutter_barcode_scanner#41]
When run in android studio I get the following message:

Xcode's output:
↳
    error: Unexpected duplicate tasks:
    1) Target 'flutter_barcode_scanner' (project 'Pods') has copy command from '/Users/hapo/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_barcode_scanner-0.1.7/ios/Classes/resource.bundle/ic_flash_on.png' to '/Users/hapo/dev/work_space/flutter/simple_cmms_demo/build/ios/Debug-iphoneos/flutter_barcode_scanner/flutter_barcode_scanner.framework/ic_flash_on.png'
    2) Target 'flutter_barcode_scanner' (project 'Pods') has copy command from '/Users/hapo/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_barcode_scanner-0.1.7/ios/Classes/resource.bundle/ic_flash_on.png' to '/Users/hapo/dev/work_space/flutter/simple_cmms_demo/build/ios/Debug-iphoneos/flutter_barcode_scanner/flutter_barcode_scanner.framework/ic_flash_on.png'
    error: Unexpected duplicate tasks:
    1) Target 'flutter_barcode_scanner' (project 'Pods') has copy command from '/Users/hapo/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_barcode_scanner-0.1.7/ios/Classes/resource.bundle/ic_flash_off.png' to '/Users/hapo/dev/work_space/flutter/simple_cmms_demo/build/ios/Debug-iphoneos/flutter_barcode_scanner/flutter_barcode_scanner.framework/ic_flash_off.png'
    2) Target 'flutter_barcode_scanner' (project 'Pods') has copy command from '/Users/hapo/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_barcode_scanner-0.1.7/ios/Classes/resource.bundle/ic_flash_off.png' to '/Users/hapo/dev/work_space/flutter/simple_cmms_demo/build/ios/Debug-iphoneos/flutter_barcode_scanner/flutter_barcode_scanner.framework/ic_flash_off.png'
    note: Using new build systemnote: Planning buildnote: Constructing build description

But, When I change the Deployment Version to 10 in Xcode it runs.

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 12

**Comment by AmolGangadhare** [comment]
Thanks for using the plugin.

The plugin is build to support backward compatibility. Is there any requirement for jump deployment target to 11 or 12?

**Comment by AmolGangadhare** [comment]
Try to clean build project once.
1. pod install
2. open project using .xcworkspace

**Comment by AmolGangadhare** [comment]
Similar to #37 

This issue has been resolved. It will be available in the new release.

**Comment by AmolGangadhare** [comment]
V1.0.0 has been released


closing this issue, feel free to reopen If the issue persisits
