### ISSUE TITLE
iOS landscape orientation error

### ISSUE THREAD

**Issue by marcelofb** [AmolGangadhare/flutter_barcode_scanner#43]
**Describe the bug**
When rotating the device the camera does not rotate.

**To Reproduce**
Call FlutterBarcodeScanner.scanBarcode() and rotate the device.

**Expected behavior**
That the camera rotate with the device.

**Screenshots**
![18227](https://user-images.githubusercontent.com/10368592/67126028-78927f80-f1cc-11e9-965a-a81a1fda46cf.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS13.1.3

**Comment by Mythar** [comment]
Also, if you change orientation while scanning, overlay is not re-centered.

**Comment by AmolGangadhare** [comment]
This issue has been resolved and will be available in the next release.

**Comment by AmolGangadhare** [comment]
V1.0.0 has been released

There is a minor overlay issue persist and it will be resolved in the next release.

Closing this issue as of now, feel free to reopen
