### ISSUE TITLE
Add possibility to switch from back to front-facing camera

### ISSUE THREAD

**Issue by bidouilles** [AmolGangadhare/flutter_barcode_scanner#46]
**Is your feature request related to a problem? Please describe.**
In some use cases when used with a tablet on a stand, the front-facing camera barcode scan will be great.

**Describe the solution you'd like**
Having an extra parameter at initialization time and/or button in UI to switch.

**Describe alternatives you've considered**
N/A

**Comment by moseskarunia** [comment]
This is the previous library for scanning barcode which I used for flutter. Unfortunately, it got discontinued, and can no longer compiles for ios, so I had to ditch it. Would be great if it can be some sort of reference to develop this feature in future update.

https://pub.dev/packages/barcode_scan
https://github.com/mintware-de/flutter_barcode_reader

**Comment by stefanodecillis** [comment]
Hello, is it possible now to flip the camera?

**Comment by izzyaf** [comment]
This should be fixed by this PR: https://github.com/AmolGangadhare/flutter_barcode_scanner/pull/184.

For anyone in need of a temporary solution while waiting for the above PR to be merged, setup `flutter_barcode_scanner` like this in your `pubspec.yaml`:

```yaml
flutter_barcode_scanner:
    git:
      url: git@github.com:izzyaf/flutter_barcode_scanner.git
      ref: master
```

**Comment by krish-dev-7** [comment]
how to hide camera switching option?

**Comment by ErWeiss-LHIND** [comment]
> how to hide camera switching option?

Yeah would love to know that too. I want to hide the camera switch button. A flag to do so would be great
