### ISSUE TITLE
iOS build release fail

### ISSUE THREAD

**Issue by JinG312** [AmolGangadhare/flutter_barcode_scanner#49]
**Describe the bug**
Some error appear when I tried to build release for iOS, below is the error I'm having:
Running Xcode build...                                                  
Xcode build done.                                            1.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    error: Unexpected duplicate tasks:
    1) Target 'flutter_barcode_scanner' (project 'Pods') has copy command from '/Users/jing/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_barcode_scanner-0.1.7/ios/Classes/resource.bundle/ic_flash_off.png' to
    '/Users/jing/Documents/All_Flutter_Project/onair_flutter/build/ios/Release-iphoneos/flutter_barcode_scanner/flutter_barcode_scanner.framework/ic_flash_off.png'
    2) Target 'flutter_barcode_scanner' (project 'Pods') has copy command from '/Users/jing/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_barcode_scanner-0.1.7/ios/Classes/resource.bundle/ic_flash_off.png' to
    '/Users/jing/Documents/All_Flutter_Project/onair_flutter/build/ios/Release-iphoneos/flutter_barcode_scanner/flutter_barcode_scanner.framework/ic_flash_off.png'
    error: Unexpected duplicate tasks:
    1) Target 'flutter_barcode_scanner' (project 'Pods') has copy command from '/Users/jing/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_barcode_scanner-0.1.7/ios/Classes/resource.bundle/ic_flash_on.png' to
    '/Users/jing/Documents/All_Flutter_Project/onair_flutter/build/ios/Release-iphoneos/flutter_barcode_scanner/flutter_barcode_scanner.framework/ic_flash_on.png'
    2) Target 'flutter_barcode_scanner' (project 'Pods') has copy command from '/Users/jing/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_barcode_scanner-0.1.7/ios/Classes/resource.bundle/ic_flash_on.png' to
    '/Users/jing/Documents/All_Flutter_Project/onair_flutter/build/ios/Release-iphoneos/flutter_barcode_scanner/flutter_barcode_scanner.framework/ic_flash_on.png'
    note: Using new build systemnote: Planning buildnote: Constructing build description

Encountered error while building for device.

Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G1012, locale en-MY)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)

• No issues found!

**To Reproduce**
Steps to reproduce the behaviour:
1)  run "flutter build ios --release -t lib/yourmain.dart" in terminal

**Comment by AmolGangadhare** [comment]
Try to clean build project once.

pod install
open project using .xcworkspace

**Comment by jackdreilly** [comment]
Same problem, and the propsed solution does not work

**Comment by AmolGangadhare** [comment]
@jackdreilly  Thanks for the confirmation.

Can you give me some details?
1. Are you trying to run the example in the same plugin?
2. Have you followed all the steps given in README to use it in project?

**Comment by AmolGangadhare** [comment]
Also, there is a workaround to get it to work.

Open project in **XCode** -> **File** -> **Workspace settings** -> **Build system** = **select legacy build system** 


Click on done and try to run the app/build with the command


Will keep updated on this....

**Comment by jackdreilly** [comment]
As, well, after making the following change in
`flutter_barcode_scanner.podspec` it also worked:

```
s.source_files = 'Classes/**/*.{swift,h,m}'
```

**Comment by JinG312** [comment]
@AmolGangadhare I've tried a clean build and the workaround,  the error still remains.

**Comment by renan002** [comment]
Same problem here, flutter run works, but flutter build ios doesn't

**Comment by AmolGangadhare** [comment]
This issue has been resolved. It will be available in the new release.

**Comment by fyeeme** [comment]
@AmolGangadhare  hope new version would be release soon

**Comment by AmolGangadhare** [comment]
V1.0.0 has been released, 

this issue has been resolved.

Closing this, please feel free to reopen if the issue persists
