### ISSUE TITLE
IOS build error

### ISSUE THREAD

**Issue by Alezhka** [AmolGangadhare/flutter_barcode_scanner#5]
Hi. I convert my flutter objc code to swift and i have some error. Help please...

```
    In module 'flutter_barcode_scanner' imported from /Users/alezhka/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_barcode_scanner-0.0.7/ios/Classes/FlutterBarcodeScannerPlugin.m:2:
    /Users/alezhka/Workspace/Funtick-mobile/build/ios/Debug-dev-iphoneos/flutter_barcode_scanner/flutter_barcode_scanner.framework/Headers/FlutterBarcodeScannerPlugin.h:3:12: note: previous definition is here
    @interface FlutterBarcodeScannerPlugin : NSObject<FlutterPlugin>
               ^
    1 error generated.

```

**Comment by AmolGangadhare** [comment]
Hi @Alezhka ,
You might have missed something while setting up iOS. Please follow the steps below:

## If you are creating a new project:
 - Command-line: Use command **flutter create -i swift -a java 'project_name'**
 - Android Studio: Check **Include Swift support for iOS code** while creating a project.

## If you already have a project:
 - You need a ios project with swift. So you can do a workaround. Just create a new flutter project with the same name at a different location. Then copy the 'iOS' folder and replace this at your existing flutter project. Just make sure, if you have made any changes earlier don't forget to do those in this project also. Now the open the XCode and change the Project and Runner iOS Deployment target to 10 as this plugin support on and above 10. Change the swift version to 5 which is latest for both Runner and Project. 
- You may see any errors of deprecation which you can fix in XCode.
- Now just run pod install and run the project.


If you still face any issue, let me know the steps you followed.

**Comment by Alezhka** [comment]
Thank you. I created new project and completely re-configured it.
