### ISSUE TITLE
It works very slow, even it doesn't even work

### ISSUE THREAD

**Issue by IsanorLopez** [AmolGangadhare/flutter_barcode_scanner#50]
**Describe the bug**
I developed the app based on its documentation and when using the scanner I do not receive an answer, that is, it does not read and when it comes to reading it takes more than 3 minutes with the immobile device but it is only times, 1 of 10 attempts, the codes are printed and is well focused

**To Reproduce**
1. Click on 'floating action button'
2. the screen apper.
3. i give permission 
4. i dont recibe anserw.

**Smartphone (please complete the following information):**
 - Device: [Motorola E4 plus]
 - OS: [Android 7.1.1]

**Additional context**
I test with others version but the issue is the same

**Comment by AmolGangadhare** [comment]
Hello,

I was not able to reproduce this issue at my end.

V1.0.0 has been released, can you try it on the latest and confirm the same?

**Comment by AmolGangadhare** [comment]
Is this issue resolved?

**Comment by IsanorLopez** [comment]
yes, apparently the problem was the device I used to test, thanks for the follow-up
