### ISSUE TITLE
Leading zeroes in barcodes are truncated

### ISSUE THREAD

**Issue by chukwumaokere** [AmolGangadhare/flutter_barcode_scanner#54]
**Describe the bug**
Whenever I scan a barcode like this: 
![image](https://user-images.githubusercontent.com/16673873/69062684-e8b93e80-09e0-11ea-893c-5a79b8052a41.png) 
The result that gets printed is only the digits after the leading zeroes. 

**To Reproduce**
1. Go to the barcode scanner app
2. Scan the barcode attached
3. Check result

**Expected behavior**
When the barcode is scanned, the value should be 00002408, not 2408. 

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: 13

**Additional context**
I take the value and I run these functions: 
```
...

sBarcode(someVal) async {
  String bCode = await FlutterBarcodeScanner.scanBarcode("#ff6666", "Cancel", true);
  print(bCode);
  someVal.enterBarcode(bCode);
  return;
}
...
enterBarcode(barc) {
  flutterWebViewPlugin.evalJavascript(`document.getElementById('barcodenumber').value="${barc}";`);
  }
```

**Comment by irperera** [comment]
interesting, for me it adds a extra 0. hmm

**Comment by AmolGangadhare** [comment]
Hi @chukwumaokere 

I've checked the barcode, it is working fine. I've tested it on `iPhone 8 plus (13.2.2)`.

One more thing,
```
sBarcode(someVal) async {
  String bCode = await FlutterBarcodeScanner.scanBarcode("#ff6666", "Cancel", true);
  print(bCode);    -> What does it print?
  someVal.enterBarcode(bCode);
  return;
}
```

Here, in print statement what does it prints?

**Comment by AmolGangadhare** [comment]
@chukwumaokere 

I'm not able to reproduce this issue on both Android and iOS.

Can you confirm the same?

**Comment by chukwumaokere** [comment]
I've modified my code to add the leading zeroes programatically using javascript, since all my barcodes are always 8 digits long, so right now im not necessarily "having" the issue but It would exist if I removed my workaround

**Comment by AmolGangadhare** [comment]
@chukwumaokere Can you post some sample code with which you are facing the issue so that I can try to reproduce this?

**Comment by chukwumaokere** [comment]
Im attaching it 
![test](https://user-images.githubusercontent.com/16673873/69895532-3bef9300-12f7-11ea-953a-f35eb964787b.png) 

This is a barcode type: Interleaved2of5
Whenever I scan this barcode I expect the result to be 00002463 but I'm getting "1331" as a result

Any ideas why?
I've been trying to debug this

**Comment by chukwumaokere** [comment]
Nevermind I've solved the error.
Instead of doing this:


```
sBarcode(someVal) async {
  String bCode = await FlutterBarcodeScanner.scanBarcode("#ff6666", "Cancel", true);
  print(bCode);
  someVal.enterBarcode(bCode);
  return;
}
...
enterBarcode(barc) {
  flutterWebViewPlugin.evalJavascript(`document.getElementById('barcodenumber').value="${barc}";`);
  }
```

Do this


```
sBarcode(someVal) async {
  String bCode = await FlutterBarcodeScanner.scanBarcode("#ff6666", "Cancel", true);
  print(bCode);
  someVal.enterBarcode(bCode);
  return;
}
...
enterBarcode(barc) {
    String js = "document.getElementById('barcodenumber').value='$barc'";
    flutterWebViewPlugin.evalJavascript(js);
	flutterWebViewPlugin.evalJavascript("document.getElementById('barcodenumber').dispatchEvent(event)");
  }
```
