### ISSUE TITLE
Problem with VCard

### ISSUE THREAD

**Issue by git-xbits** [AmolGangadhare/flutter_barcode_scanner#55]
When I Try to read a Vcard QRcode, I get empty string from method or return just first data from String.

E.G Above;

![image](https://user-images.githubusercontent.com/46821431/69187881-2e1d5f00-0afa-11ea-8ea6-79cb32cd3a83.png)

version flutter_barcode_scanner: ^0.1.7;

**Comment by git-xbits** [comment]
Update:

In IOS work fine. Unfortunatelly in Android don't work.

**Comment by AmolGangadhare** [comment]
@git-xbits 

Thanks for reporting the issue.

This has been resolved. It will be available in the upcoming release. I will notify you whenever the next release is available.

**Comment by AmolGangadhare** [comment]
V1.0.0 has been released, can you try it on the latest and confirm the same?
