### ISSUE TITLE
QR-code content is parsed/modified on Android

### ISSUE THREAD

**Issue by magnuswikhog** [AmolGangadhare/flutter_barcode_scanner#62]
**Describe the bug**
When scanning QR-codes that contain "structured data", for example 
    
`mailto:email@example.com`
`tel:555-1234`
`MECARD:N;Joe;EMAIL:joe@example.com`

some information is lost due to some kind of parsing it seems. The above result in 

`email@example.com`
`555-1234`
`Joe`

on Android (7.0) but in the original content on iOS.

**To Reproduce**
1. Go to http://qrcode.meetheed.com/qrcode_examples.php
2. Scan some of the QR-codes with an Android phone
3. Observer the output from `FlutterBarcodeScanner.scanBarcode()`

**Expected behavior**
The actual content of the QR-code should be returned.

**Smartphone (please complete the following information):**
 - Device: Huawei Honor 6x
 - OS: Android 7.0
 - flutter_barcode_scanner 0.1.7

**Comment by AmolGangadhare** [comment]
V1.0.0 has been released, can you try it on the latest and confirm the same?

**Comment by AmolGangadhare** [comment]
This issue has been resolved in the latest update.

Closing this as there is no response, feel free to report a new issue if the issue persists.

**Comment by afifahsalimi** [comment]
I have qr code which contains this string 'hello\nworld' but when scanning on Android, the result gives 'hello' only. It got cut after this character '\n'.
