### ISSUE TITLE
how to remove line 

### ISSUE THREAD

**Issue by luckymehndiratta** [AmolGangadhare/flutter_barcode_scanner#67]
what should i do for remove line

**Comment by AmolGangadhare** [comment]
There is no feature to hide the scan line at this moment. Still, you can use a hack.

Just provide transparent hex color code while calling `scanBarcode` or `getBarcodeStreamReceiver `

**Comment by AmolGangadhare** [comment]
Closing this issue as there is no response,

Feel free to reopen
