### ISSUE TITLE
App crashes when permission is denied in Android

### ISSUE THREAD

**Issue by talhazzani** [AmolGangadhare/flutter_barcode_scanner#70]
Greetings, 
I found that many users have had a crash related to the barcode scanner , after some investigations ,I found that those users denied permission to use the camera.

Note: All users are using android. 

Please  let me know how to handle this

Thanks

**Comment by allefsousa** [comment]
Same problem here, some solution ?

**Comment by AmolGangadhare** [comment]
@talhazzani @allefsousa 

Can you post any error logs? That would be more helpful to fix the issue.

Thanks

**Comment by FranciscoBeccuti** [comment]
Hi. I have the same problem.
I cannot generate a LOG with the error.
Reproducing the problem is easy, removing camera permissions to the APP.

**Comment by AmolGangadhare** [comment]
V1.0.0 has been released, can you try it on the latest and confirm the same?

**Comment by AmolGangadhare** [comment]
It looks like this issue has been resolved in V1.0.0, so closing this issue. Please don't hesitate to open a new issue if the issue persists.
