### ISSUE TITLE
A Quick Fix for "FlutterEngine" call issue

### ISSUE THREAD

**Issue by dhruvilp** [AmolGangadhare/flutter_barcode_scanner#71]
**PROBLEM**
Flutter no longer calls a new FlutterEngine on onCreate() which causes a crash after APK build.

**SOLUTION**
Go to ==>
```flutter_barcode_scanner/example/android/app/src/main/java/com/amolg/flutterbarcodescannerexample/EmbeddingV1Activity.java```

and **REPLACE** following

```import android.os.Bundle
import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class EmbeddingV1Activity: FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(this)
    }
}

**Comment by AmolGangadhare** [comment]
@dhruvilp 

Thanks for reporting the issue.

This migration is already done. It will be available in next release.

Thanks

**Comment by MysthawkCanada** [comment]
Hello,

Is there a way to fix this temporarily until your next release is available?  I don't really follow dhruvilp's comment so I don't know how to fix it myself as I'm not a Java guy.

Thank you,
Michael

**Comment by AmolGangadhare** [comment]
@MysthawkCanada 

Please follow https://github.com/AmolGangadhare/flutter_barcode_scanner/issues/60#issuecomment-575516231

**Comment by MysthawkCanada** [comment]
@AmolGangadhare 

Perfect, thank you!

**Comment by dhruvilp** [comment]
> @dhruvilp
> 
> Thanks for reporting the issue.
> 
> This migration is already done. It will be available in next release.
> 
> Thanks

Thanks, Amol for getting back!

**Comment by AmolGangadhare** [comment]
V1.0.0 has been released

Closing this
