### ISSUE TITLE
What is the needed API level for the scanner to run.

### ISSUE THREAD

**Issue by Crazyfr0g** [AmolGangadhare/flutter_barcode_scanner#72]
I am experiencing crashes in my app everytime I try to do a scan. I am using android 6 (Marshmallow). Is it because of my type of android? or need to configure something in my code? The way I try todo a scan is, I have a button named "scan" and if you click it the scanner will appear. But in my personal phone. Everytime I try to do that. My app crashes, but in my emulator using android (Nougat) it is running fine. Does this scanner need to be android 7.1 to run? Thank you in advance.

**Comment by AmolGangadhare** [comment]
@Crazyfr0g 

Thanks for reporting the issue.

Can you add some error logs for reference?

Thanks

**Comment by Crazyfr0g** [comment]
There is actually no error showing sir @AmolGangadhare. The app just crash everytime I try to do a scan.

**Comment by Crazyfr0g** [comment]
But when I tried it in my other personal phone which uses OREO. It runs perfectly sir. The problem only occurs when I use my app in Marshmallow.

**Comment by AmolGangadhare** [comment]
Ok, thanks for the details.  Allow me some time to reproduce this issue. I'll update you on this.


Thanks

**Comment by Crazyfr0g** [comment]
Thank you sir @AmolGangadhare

**Comment by AmolGangadhare** [comment]
V1.0.0 has been released, can you try it on the latest and confirm the same?

**Comment by AmolGangadhare** [comment]
Closing this issue as there is no response, feel free to open a new issue if the issue persists.
