### ISSUE TITLE
Not working on Pixel 4XL

### ISSUE THREAD

**Issue by EmixamZ** [AmolGangadhare/flutter_barcode_scanner#75]
Good Afternoon, 

As stated in the title, the window to scan the QR code does not appear and there's no log on the console. 

Let me know what information you need to help you on this. 

Many thanks !

**Comment by AmolGangadhare** [comment]
@EmixamZ 
Thanks for reporting the issue.

Give me some time to reproduce this issue.

Thanks

**Comment by AmolGangadhare** [comment]
V1.0.0 has been released, can you try it on the latest and confirm the same?

**Comment by AmolGangadhare** [comment]
@EmixamZ Can you provide sample QR code you are using?

**Comment by EmixamZ** [comment]
Good Afternoon @AmolGangadhare , 
Unfortunately i'm still encountering an issue. 

> MissingPluginException (MissingPluginException(No implementation found for method scanBarcode on channel flutter_barcode_scanner))


I have copy and paste the code from : 
https://pub.dev/packages/flutter_barcode_scanner#-example-tab-

**Comment by AmolGangadhare** [comment]
Can you create new app and try to use it in?
Also have you tried 1.0.1?

**Comment by EmixamZ** [comment]
I have created a new app just for the test to make sure there is no other dependencies: 

`dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_barcode_scanner: 1.0.1`

This is my pubspec
Should I also update flutter ?

**Comment by AmolGangadhare** [comment]
Which flutter version are you using?

**Comment by EmixamZ** [comment]
I was using 1.12, 
I have now upgraded the version to 1.17.1 and it's now working !
