### ISSUE TITLE
crashes on flutter stable 1.12.13+hotfix.8 channel

### ISSUE THREAD

**Issue by NTMS2017** [AmolGangadhare/flutter_barcode_scanner#79]
I place an issue on flutter but I found out that flutter_barcode_scanner: ^0.1.7 crashes on app start.
Any idea? Need urgent help?

**Comment by fikurniawan** [comment]
> I place an issue on flutter but I found out that flutter_barcode_scanner: ^0.1.7 crashes on app start.
> Any idea? Need urgent help?

me too, so i downgrade to flutter stable v1.9.1+hotfix 6

**Comment by mklepaczko** [comment]
It seems that most reader packages have a problem with that, looking forward to the new version

**Comment by AmolGangadhare** [comment]
V1.0.0 has been released

closing this
