### ISSUE TITLE
Flashlight icon not visible on ios

### ISSUE THREAD

**Issue by Xgamefactory** [AmolGangadhare/flutter_barcode_scanner#82]
How to achive flashlight icon to be visible inside 3 dot flashlight text for ios
![IMG_00FA99A62996-1](https://user-images.githubusercontent.com/22529051/75563730-44757800-5a64-11ea-87f0-ccee92a61c15.jpeg)

**Comment by AmolGangadhare** [comment]
V1.0.0 has been released, can you try it on the latest and confirm the same?

**Comment by famazi111** [comment]
> V1.0.0 has been released, can you try it on the latest and confirm the same?

Still the same for me on the latest version.

**Comment by roback7** [comment]
Also seeing the F..h on the lastest version on iOS 13.4

**Comment by AmolGangadhare** [comment]
This issue has been resolved and will be available in the coming release V1.0.1

**Comment by AmolGangadhare** [comment]
Closing this issue as its been fixed in V1.0.1

**Comment by arifjmamun** [comment]
The issue still exists and not showing the icon in iOS.

**Comment by Riscait** [comment]
@AmolGangadhare 
I updated to ^1.0.1, but I get "F.. .h" on my iPhone 8 with iOS 14.1.
Flutter 1.22.4
flutter_barcode_scanner: ^1.0.1
