### ISSUE TITLE
I am seeing MissingPluginException

### ISSUE THREAD

**Issue by anwesh408** [AmolGangadhare/flutter_barcode_scanner#86]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method scanBarcode on channel flutter_barcode_scanner)

**Comment by AmolGangadhare** [comment]
V1.0.0 has been released, can you try it on the latest and confirm the same?

**Comment by AmolGangadhare** [comment]
Closing the issue as there is no response on this.
