### ISSUE TITLE
FlutterBarcodeScanner unable to catch Camera not available exception

### ISSUE THREAD

**Issue by Xgamefactory** [AmolGangadhare/flutter_barcode_scanner#87]
when trying to run await FlutterBarcodeScanner.scanBarcode unable to catch this exception plugin just shows alert dialog and not rethrow error

 ```
String res;
    try {
      res = await FlutterBarcodeScanner.scanBarcode(
          "#F04F33", "Cancel", true, ScanMode.BARCODE);
    } on PlatformException catch (e) {
//never calling
      throw Exception(e.message);
    }
```

**Comment by AmolGangadhare** [comment]
Thanks for reporting the issue.
Can you add some error logs, please?

Currently, V1.0.0 has been released, can you try it on the latest version?

**Comment by Xgamefactory** [comment]
instead of showing dialog in plugin side it would be nice to throw error so developers can catch  it.

**Comment by AmolGangadhare** [comment]
The errors are managed in the native part for both android and ios as the scanning is done in the native part.
Currently, there is no functionality to get the error from the native to the flutter app as the required permissions/ error handling is already done at the native code.

**Comment by AmolGangadhare** [comment]
Closing this as there is no response. Feel free to open a new issue.
