### ISSUE TITLE
iOS build error with codemagic

### ISSUE THREAD

**Issue by rsunmoto** [AmolGangadhare/flutter_barcode_scanner#9]
**Describe the bug**
project with this plugin failed to build for iOS on codemagic.io
error reported: 'flutter_barcode_scanner/FlutterBarcodeScannerPlugin.h' file not found

**Full error log**
== Building for iOS ==

== /usr/local/bin/flutter build ios --release --no-codesign ==
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.abatix.test1 for device (ios-release)...
Running pod install...                                              1.9s
Running Xcode build...                                          
Xcode build done.                                           52.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    /Users/builder/clone/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'flutter_barcode_scanner/FlutterBarcodeScannerPlugin.h' file not found
    #import <flutter_barcode_scanner/FlutterBarcodeScannerPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Encountered error while building for device

**To Reproduce**
1. import the lib in an existing project in android studio
2. enable swift by creating another app and replace ios folder
3. specify deployment target by manually creating a Podfile in ios folder with following content
![image](https://user-images.githubusercontent.com/24903447/57037081-cd8d0a00-6c1b-11e9-9fe2-25cbe3d64919.png)
4. Import to codemagic and build for ios
5. See error

**Expected behavior**
ios build successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/24903447/57036961-6f602700-6c1b-11e9-944e-13b63c246495.png)

**Comment by AmolGangadhare** [comment]
Hi @rsunmoto ,
I've updated the plugin with a hotfix. Also please uncomment the `use_frameworks!` and try again.
If the issue still occurs please feel free to report.

**Comment by AmolGangadhare** [comment]
The issue has been resolved in the latest release, so closing this.

**Comment by amrosama2020** [comment]
Thanks for the great plugin, I had the same issue with latest version on both local builds with target set to 10 and swift version set to 5

I tried latest version on pub.dev and master branch on git hub and both gave the same error :
`'flutter_barcode_scanner/FlutterBarcodeScannerPlugin.h' file not found
#import <flutter_barcode_scanner/FlutterBarcodeScannerPlugin.h>`

The only thing that fixed it for me was changing this change:
https://github.com/EFG-Hermes/flutter_barcode_scanner/commit/6d9ffdede298a341ca94e9a75b5d8dae5e8ad6aa

Not sure if this is a good resolution but it works for me.

**Comment by AmolGangadhare** [comment]
@amrosama2020 Does this works in all scenarios?

**Comment by amrosama2020** [comment]
> @amrosama2020 Does this works in all scenarios?

Yes, it works 

also FYI, the issue was occurring in appcenter.ms builds and local builds
