### ISSUE TITLE
Missing header file?

### ISSUE THREAD

**Issue by lookfirst** [AmolGangadhare/flutter_barcode_scanner#92]
**Describe the bug**
xcode is telling me it cannot find this file... 

`#import <flutter_barcode_scanner-Swift.h>`

it works fine if i hack it back to what it was before...

`#import <flutter_barcode_scanner/flutter_barcode_scanner-Swift.h>`

**Comment by knaeckeKami** [comment]
see #89

**Comment by lookfirst** [comment]
thanks @knaeckeKami ... could you add something about 'header file' in your issue title? Would make it easier to find.
