### ISSUE TITLE
import android.hardware.Camera has been deprecated

### ISSUE THREAD

**Issue by Ohpizarro** [AmolGangadhare/flutter_barcode_scanner#94]
**Describe the bug**
\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_barcode_scanner-1.0.0\android\src\main\java\com\amolg\flutterbarcodescanner\BarcodeCaptureActivity.java:28: warning: [deprecation] Camera in android.hardware has been deprecated

**To Reproduce**
flutter build appbundle

**Smartphone (please complete the following information):**
- Device Android

**Comment by AmolGangadhare** [comment]
The plugin uses VIsionAPI which is deprecated that's why this warning is appearing.

The plugin will be migrated to MLKit for the android part after that it won't show these warnings.

**Comment by AmolGangadhare** [comment]
Thanks for using the plugin.

The ML Kit migration is under evaluation, after which the warning won't be flashing anymore. 

Closing this issue as there is already a feature request for ML Kit migration.
