### ISSUE TITLE
Error connecting to the service protocol

### ISSUE THREAD

**Issue by Emarcode** [AmolGangadhare/flutter_barcode_scanner#95]
Error connecting to the service protocol: failed to connect to http://127.0.0.1:16865/1VC6_1oWWdg=/
app failed to build
flutter_barcode_scanner: ^1.0.0

![ScreenShot_20200512115634](https://user-images.githubusercontent.com/45165138/81670315-b6484580-9447-11ea-9d86-cd4d65a22d6d.png)

**Comment by Loucif-Fouad** [comment]
Just Downgraded to Flutter v1.7.0 and it works.

**Comment by Emarcode** [comment]
> 
> 
> Just Downgraded to Flutter v1.7.0 and it works.

thanks my friend i used another plugin and it works fine

**Comment by zwells** [comment]
Any fix for this besides downgrading?

**Comment by Loucif-Fouad** [comment]
> > Just Downgraded to Flutter v1.7.0 and it works.
> 
> thanks my friend i used another plugin and it works fine

can you share with us the package that works for you?

**Comment by Emarcode** [comment]
> 
> 
> > > Just Downgraded to Flutter v1.7.0 and it works.
> > 
> > 
> > thanks my friend i used another plugin and it works fine
> 
> can you share with us the package that works for you?

[https://pub.dev/packages/qrscan#-readme-tab-](url)

**Comment by AmolGangadhare** [comment]
@Emarcode 

Sorry for the delayed reply.

1. Is this issue rise on ios device or on both?
2. Does this issue rise with this plugin or still rise without using?
Also, there is a known issue in flutter framework.

Please refer to this link https://github.com/flutter/flutter/issues/47204 , it have some possible fixes

**Comment by AmolGangadhare** [comment]
Please upgrade to the latest Flutter version and V 2.0.0 for the plugin.

**Comment by AmolGangadhare** [comment]
Closing this due to no response from the user.
